### ISSUE TITLE
List dependencies

### ISSUE THREAD

**Issue by stubb** [buzz/volctl#1]
I would appreciate a complete list of the necessary dependencies to get your pythonscript running.
Looks like https://github.com/Valodim/python-pulseaudio and python2-gobject is required.
Seems like the server providing the libpulseaudio package in the venv script is down.

volctl looks like a promising project!

**Comment by buzz** [comment]
Hey, on travels... can look into this when I'm back in February... Sorry.
But should be fairly easy to get this running. Build the Valodim/python-pulseaudio yourself. It's just a thin ctypes wrapper lib. Rerun the script until no import errors remain. You can do it!

Happy for feedback :)

**Comment by buzz** [comment]
Fixed in 5fa2e4f7766eb09fc6cd3829fda3ce0119517ef4 :)

**Comment by stubb** [comment]
Thanks for clarifying it. Iam trying to use this on arch linux but the python pulseaudio lib throws an error:
```
Traceback (most recent call last):
  File "volctl.py", line 6, in <module>
    from pulseaudio.lib_pulseaudio import PA_VOLUME_MUTED, PA_VOLUME_NORM, \
  File "/usr/lib/python2.7/site-packages/pulseaudio/__init__.py", line 29, in <module>
    class PulseAudio(gobject.GObject):
  File "/usr/lib/python2.7/site-packages/gi/__init__.py", line 62, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

```

Maybe iam going to create a PR for python pulseaudio...

**Comment by buzz** [comment]
I think you have installed sbillaudelle/python-pulseaudio (through a package manager?).
Have you tried Valodim/python-pulseaudio?

**Comment by stubb** [comment]
Yep I had it installed via the package management, but already tried the newer version from Valodim with no luck. Sadly havnt much time to investigate right now.
