### ISSUE TITLE
Settings schema 'apps.volctl' is not installed

### ISSUE THREAD

**Issue by dagoll** [buzz/volctl#14]
Hi, @buzz 

I just updated volctl on the Arch via AUR. And I have a problem when running volctl after updated, which displays the following message:

`GLib-GIO-ERROR **: Settings schema 'apps.volctl' is not installed`

What can I do to volctl can run normally as before the update?
Please help, thanks.

**Comment by buzz** [comment]
Hey @dagoll 

This is an Arch/AUR package issue I think. Could you re-post here, please:
https://aur.archlinux.org/packages/volctl/

Thanks for the feedback!

**Comment by buzz** [comment]
fix in d926060430d98e8a20279b720fbb1c5282e1949e

**Comment by buzz** [comment]
@dagoll Try to reinstall using AUR. Should work now.

**Comment by JcKlomp** [comment]
This still requires glib-compile-schemas to be run when one installs from git. Would be nice to have this documented somewhere.

**Comment by buzz** [comment]
@JcKlomp Did so: 2f38d57c5f2b110df5bfbcd79725954d6f3cc5c8
