### ISSUE TITLE
Configuration option to prevent pop-up on volume change

### ISSUE THREAD

**Issue by AntiCompositeNumber** [buzz/volctl#16]
I have an IRC client (HexChat) that only appears as playing audio for about 1s, while the notification sound plays. This makes volctl update twice, stealing focus. It would be useful to be able to disable the popup-on-volume-change behavior, or prevent it from popping up when applications are added/removed.

**Comment by TonyMorehen** [comment]
I really like volctl, particularly the mute function.  However, the frequent popups to announce new programs or volume changes are very distracting.  Please give us the option to disable.  Thanks.

**Comment by buzz** [comment]
Thanks for your feedback. :heart: 

I'm currently overhauling the whole code base. The new release will have this option.
You can track progress in the dev branch.
