### ISSUE TITLE
Support multiple screens

### ISSUE THREAD

**Issue by buzz** [buzz/volctl#22]
> @ScuttleSE https://github.com/buzz/volctl/issues/7#issuecomment-509487527
> I'm on a three monitor setup, and the slider-popups opens up almost in the middle of my middle monitor instead of on top of the tray icon, which is also on the middle screen.
> 
> My guess is that the program gets the resolution of my left or right monitor and uses that for the positioning instead of the middle one.

**Comment by buzz** [comment]
@ScuttleSE Could you check if the issue still exists? I'm unable to verify as I currently don't have a multi-screen setup available for testing.

**Comment by ScuttleSE** [comment]
WIth the 0.7.4 release I get the same phenomenon. My tray-area is on the bottom right, when I left-click the volctl icon I get the sliders almost all the way to the right on the screen

**Comment by buzz** [comment]
Can you provide a screenshot?
What Window Manager do you use?

**Comment by ScuttleSE** [comment]
![screenshot-2020-08-08_20:36:25](https://user-images.githubusercontent.com/4344284/89717422-dcce3c00-d9b6-11ea-811f-63681fe045a5.png)

Using i3 as wm

**Comment by buzz** [comment]
Can you try `v0.7.5`? Slider window positioning has been rewritten. Maybe it works for you. Otherwise I would need access to a multi-monitor setup to debug this.

**Comment by ScuttleSE** [comment]
0.7.5 seems to do the same thing

**Comment by buzz** [comment]
@ScuttleSE Could you check `v0.8.0` which includes @notfound4 patch?

**Comment by ScuttleSE** [comment]
Yep, now the popup-slides appear just where they are supposed to :)

**Comment by buzz** [comment]
Awesome! Thanks to @notfound4
