### ISSUE TITLE
Solo/mute buttons for the tray mini mixer?

### ISSUE THREAD

**Issue by buzz** [buzz/volctl#3]
I imagine mute/solo buttons per application could be quite useful.

_Do we need this?_

**Comment by Narrat** [comment]
I would appreciate such a possebility.

**Comment by TonyMorehen** [comment]
I think this enhancement would be very useful.  Perhaps clicking the icon beneath each slider would toggle a mute for that sink/source.  Or the icon could be replaced with a mute button, preferably with the image from the icon on it.
BTW This would fix a problem I've had with mute on the right click menu.  One of my laptops can play through either its internal speakers or through external bluetooth speakers.  Mute only mutes the first, not the second.
