### ISSUE TITLE
Sometimes slider windows opens in top-left screen corner and does not disappear

### ISSUE THREAD

**Issue by buzz** [buzz/volctl#30]
https://github.com/buzz/volctl/issues/29#issuecomment-670820878
> The big issue is with the slider, sometimes when I open it, it opens in the top left corner and it does not disappear after timeout. However; this does not always happen, sometimes it works.

@justaquestion: I saw this happening very rarely. Seems to be some sort of race condition between tray icon and slider window creation. If you can find a way to reproduce this issue, I'd be very happy.

**Comment by buzz** [comment]
@justaquestion: I'm not able to reproduce the bug locally even that I also saw this happening. Could you check if you still have the bug with `v0.7.3`?

**Comment by justaquestion** [comment]
Hello, thanks. I have just intalled v 0.7.4-1 and so far everything is OK. OSD and sliders are working as expected.

**Comment by justaquestion** [comment]
Tested v0.7.4-1 a bit. It is not working well with jwm. If no GUI application is running, then slider is not shown, only OSD, if enabled. If a GUI application is running (but no application is using the sound device), the device slider is shown, but if OSD is enabled then there is an interaction between the two. If an application is using sound device then the application slider is OK, but there is still interaction between the device slider and the OSD, if the latter is enabled.

**Comment by buzz** [comment]
I'm not sure if I understand your issue correctly. Could you please test with `v0.7.5`? The window positioning was completely rewritten.

**Comment by justaquestion** [comment]
The only thing now is that if I enable OSD then the sliders no longer work (JWM, Arch Linux).

**Comment by buzz** [comment]
I tested under JWM and everything works.

Can you please elaborate on what exactly you are expecting from the program to happen and what are you seeing instead? You can also provide screenshots if helpful.
