### ISSUE TITLE
OSD not disappearing after program start

### ISSUE THREAD

**Issue by deimosfr** [buzz/volctl#31]
Hi,

I'm running Arch Linux 5.7.12-arch1-1 with volctl 0.7.2. When I'm launching volctl, I got this:

https://user-images.githubusercontent.com/22876640/89700561-12165380-d8fd-11ea-940f-2bb565e28b58.png

Until I change the volume, which then disappears. Would it be possible to not show this blank square at the start of volctl?

Thanks

**Comment by buzz** [comment]
Please check if `v0.7.3` works for you.

**Comment by deimosfr** [comment]
Perfect thanks
