### ISSUE TITLE
[Feature request] Set default sink

### ISSUE THREAD

**Issue by superpupervlad** [buzz/volctl#32]
If I had several sinks, for example, speakers and headphones, I can't set default sink, so I need to use other application for this. Maybe need to add some checkbox for this.

**Comment by buzz** [comment]
> I can't set default sink, so I need to use other application for this.

Correct: https://wiki.archlinux.org/index.php/PulseAudio/Examples#Set_the_default_output_sink

There *a lot* of different things that can be done with PulseAudio. Citing the README:

> It's not meant to be an replacement for a full-featured mixer application. If you're looking for that check out the excellent pavucontrol.
