### ISSUE TITLE
Add automatic systemd install

### ISSUE THREAD

**Issue by RiedleroD** [buzz/volctl#35]
I just installed this from the aur & I'm a bit disappointed that it doesn't have a prepackaged .service file. This program is exactly what I searched for, but this is a bit of a turndown.

**Comment by buzz** [comment]
Um... Service file? Do you mean systemd service file?

This is a desktop application. Why would you want a service file?

**Comment by RiedleroD** [comment]
because it should autostart? Also, it works just fine without a full desktop, I've got qtile (pure window manager) and it works. I just don't have any other autostart options than xinit and systemd.

**Comment by buzz** [comment]
Oh, qtile. I used that years ago and liked it quite much. :+1: 

It's not true that qtile doesn't support autostart. Read the docs:
http://docs.qtile.org/en/latest/manual/config/hooks.html#autostart

**Comment by RiedleroD** [comment]
oh lol didn't see that. Sorry for bothering you.
