### ISSUE TITLE
how can i install it on elementary os?

### ISSUE THREAD

**Issue by Alien0w0** [buzz/volctl#42]
i am trying to install this app in elementary os. when i run 
`glib-compile-schemas /usr/share/glib-2.0/schemas/`
it gives  an error

`sudo glib-compile-schemas /usr/share/glib-2.0/schemas
No such key 'button-layout' in schema 'org.gnome.mutter:Pantheon' as specified in override file '/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override'; ignoring override for this key.
No such key 'enable-animations' in schema 'org.gnome.mutter:Pantheon' as specified in override file '/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override'; ignoring override for this key.`

**Comment by buzz** [comment]
The issue seems not to be related to volctl. As long as the volctl schemas have been applied, you're good to go.
Check back with the Pantheon project to resolve the schema issue if you need to.

**Comment by Alien0w0** [comment]
thank you so much for your guidance
