### ISSUE TITLE
Add support for inputs

### ISSUE THREAD

**Issue by Dash-L** [buzz/volctl#44]
Allow controlling the volume of inputs like a microphone using `pulse.source_list()` and `pulse.source_output_list()`
I've been looking forever for a tray icon like this, so thank you! I think the only thing it's missing for me is the ability to control the volume of my microphone, both as a master volume and per app.

**Comment by buzz** [comment]
volctl has a very specific mission statement. Controlling audio inputs will likely be not a part of it in the foreseeable future.
I might consider merging such functionality if someone comes up with a rock-solid PR.
