### ISSUE TITLE
OSD in the center / in the corner settings addition 

### ISSUE THREAD

**Issue by raven2cz** [buzz/volctl#48]
Hello, very nice small python app! 

Can you just improve possibility to show OSD in the center, not in the corner?

 _move_to_corner, _move_to_center as additional parameter in the settings?

Thanks!

**Comment by buzz** [comment]
Can't promise anything, sorry. When I find the time.

**Comment by raven2cz** [comment]
I can help. But I don't understand one important point of your installation process.

I tried to make some changes to `volctl/osd.py`

call `sudo ./setup.py install`. But the `volctl` is still doesn't change. It is still installed version from aur.
I tried to delete `/usr/bin/volctl` and call `setup.py` again. the `volctl` is installed to bin, but still the previous version is called.

I tried to check what is `volctl` and it's some script which call volctl, but it seems that `volctl` is installed by python with pip, or? And there is still previous version?

I need to explain how to correctly replace correctly patched volctl version. Thx.

**Comment by buzz** [comment]
You'd want to use [setuptools Development Mode](https://setuptools.readthedocs.io/en/latest/userguide/commands.html#develop-deploy-the-project-source-in-development-mode). Combine it with Virtualenv to leave your system untouched.

It's all [explained in the README](https://github.com/buzz/volctl#development).

**Comment by raven2cz** [comment]
The PR added.

**Comment by buzz** [comment]
> The PR added.

Thank for submitted your first PR for volctl!

I'd suggest to do some spec'ing here first, before jumping straight into implementation. I also added a small review for your PR.

**Comment by raven2cz** [comment]
The PR corrections are done. If buzz will have time to merge, the issue can be closed.
