### ISSUE TITLE
No volume sliders appear if there is a non-ALSA sinks

### ISSUE THREAD

**Issue by ironss** [buzz/volctl#53]
Using git commit ffceaa72a3 (ie. latest when reported), the volume sliders do not appear with my system. The following error is reported on the console:

    File "/usr/local/lib/python3.8/dist-packages/volctl-0.9.0-py3.8.egg/volctl/slider_win.py", line 115, in create_widgets
    File "/usr/local/lib/python3.8/dist-packages/volctl-0.9.0-py3.8.egg/volctl/slider_win.py", line 143, in recreate_sliders
    KeyError: 'alsa.card_name'

`pacmd list-sinks` reports that there are 2 sinks. One of them is a filter, not an ALSA sound device, so there is no propery 'alsa.card_name'; it has only 3 properies

	properties:
		device.class = "filter"
		device.description = "Simultaneous output to Built-in Audio Analog Stereo"
		device.icon_name = "audio-card"

I made a work-around by catching the KeyError exception where it happens, and replacing the name with a dummy. But I think it would be better to filter the list of sinks (slider_win.py, line 133) to show only real output devices, perhaps using `sink.proplist['device.class'] == 'sound' ` or some other criterion.

Note that when you use volctl to adjust the level of this faulty sink 'Simultaneous output...', the corresponding slider in pavucontrol does NOT change, and vice versa. With the real ALSA device, the pavucontrol and volctl sliders stay in sync.

There seems to be something special about this sink: either this specific sink, or perhaps the entire 'filter' class of sinks.

Showing only ALSA cards is a quick fix.

**Comment by ironss** [comment]
I cannot attach a one-line patch file, so here it is
    diff --git a/volctl/slider_win.py b/volctl/slider_win.py
    index dfb360a..01f0ecd 100644
    --- a/volctl/slider_win.py
    +++ b/volctl/slider_win.py
    @@ -137,6 +137,8 @@ class VolumeSliders(Gtk.Window):
                     sinks = []
                     sink_inputs = []
     
    +            sinks = [ sink for sink in sinks if 'alsa.card_name' in sink.proplist ]
    +

**Comment by ironss** [comment]
A better idea is to replace property 'alsa.card_name' with property 'device.description' is the ALSA card name does not exist. Then we do get a volume slider for both sink 'Simultaneous output...' and sink-input 'Simultaneous output...'  -- I did not realise that these are two different things.

    diff --git a/volctl/slider_win.py b/volctl/slider_win.py
    index dfb360a..ffde03e 100644
    --- a/volctl/slider_win.py
    +++ b/volctl/slider_win.py
    @@ -139,8 +139,13 @@ class VolumeSliders(Gtk.Window):
     
             # Sinks
             for sink in sinks:
    +            try:
    +                card_name = sink.proplist["alsa.card_name"]
    +            except KeyError:
    +                card_name = sink.proplist["device.description"]
    +
                 props = (
    -                sink.proplist["alsa.card_name"],
    +                card_name,
                     "audio-card",
                     sink.volume.value_flat,
                     sink.mute,

**Comment by buzz** [comment]
Fixed in 8cd4ef451779965fd97a6b9f61e24945cbcdcf2d
