### ISSUE TITLE
Installation doesn't work on ZorinOS

### ISSUE THREAD

**Issue by KiritoStorm** [buzz/volctl#61]
I installed it like it is described, but I don't see a tray icon even after restarting.
But I didn't got an error or something, so is there a way to fix this maybe?

**Comment by buzz** [comment]
There should be errors if the status icon is not created correctly. It may also be a bugged tray icon implementation you're using. If you provide more information that would very helpful.

See also https://github.com/buzz/volctl#statustray-icon-implementation

**Comment by KiritoStorm** [comment]
Zorin is based on Ubuntu, so it should support that stuff right?
The console logs nothing when I execute the command: `sudo update-desktop-database`

However I see an output on the Zorin Logs, but I can't find a process called 'org.freedesktop.Tracker1'

14:29:32 systemd: Started Tracker metadata database store and lookup manager.
14:29:32 dbus-daemon: [session uid=1000 pid=1883] Successfully activated service 'org.freedesktop.Tracker1'
14:29:32 sudo: pam_unix(sudo:session): session closed for user root
14:29:32 systemd: Starting Tracker metadata database store and lookup manager...
14:29:32 dbus-daemon: [session uid=1000 pid=1883] Activating via systemd: service name='org.freedesktop.Tracker1' unit='tracker-store.service' requested by ':1.2' (uid=1000 pid=1881 comm="/usr/libexec/tracker-miner-fs " label="unconfined")
14:29:32 sudo: pam_unix(sudo:session): session opened for user root by (uid=0)

I looked at the output from compiling GSettings, maybe that could be also interessting for you.
I'm not a linux expert, but maybe you know what's wrong then.

14:35:13 sudo: pam_unix(sudo:session): session closed for user root
14:34:17 systemd: anacron.service: Succeeded.
14:34:17 anacron: Normal exit (0 jobs run)
14:34:17 systemd: Started Run anacron jobs.
14:33:39 cat: [531811:531811:1208/143339.112517:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.", source: chrome-extension://mpognobbkildjkofajifpdfhcoklimli/main.html (0)
14:33:26 systemd: Finished Daily apt upgrade and clean activities.
14:33:02 tracker-store: OK
14:32:48 systemd: systemd-hostnamed.service: Succeeded.
14:32:44 dbus-daemon: [session uid=1000 pid=1883] Successfully activated service 'org.gnome.gedit'
14:32:32 systemd: Started Tracker metadata database store and lookup manager.
14:32:32 dbus-daemon: [session uid=1000 pid=1883] Successfully activated service 'org.freedesktop.Tracker1'
14:32:32 systemd: Starting Tracker metadata database store and lookup manager...
14:32:32 dbus-daemon: [session uid=1000 pid=1883] Activating via systemd: service name='org.freedesktop.Tracker1' unit='tracker-store.service' requested by ':1.2' (uid=1000 pid=1881 comm="/usr/libexec/tracker-miner-fs " label="unconfined")
14:32:17 systemd: Started Hostname Service.
14:32:17 dbus-daemon: [system] Successfully activated service 'org.freedesktop.hostname1'
14:32:17 systemd: Starting Hostname Service...
14:32:17 dbus-daemon: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.207' (uid=1000 pid=537381 comm="/usr/bin/gnome-logs --gapplication-service " label="unconfined")
14:32:06 systemd: gnome-launched-xfce4-taskmanager.desktop-544411.scope: Succeeded.
14:31:50 dbus-daemon: [session uid=1000 pid=1883] Successfully activated service 'org.xfce.Xfconf'
14:31:50 systemd: Started Application launched by gnome-shell.
14:31:49 gnome-shell: Timelines with detached actors are not supported
14:31:45 systemd: gnome-launched-gnome-system-monitor-537457.scope: Succeeded.

**Comment by raven2cz** [comment]
Can you post output from console if you start volctl from cli?

**Comment by KiritoStorm** [comment]
As I said I don't see an output on the console, maybe I can try an alternative console, I used that from Zorin
![image](https://user-images.githubusercontent.com/46503102/145219643-d8e48dbf-f233-4a0c-9ce5-cfb55d54431d.png)

**Comment by buzz** [comment]
The logs you post don't say nothing about volctl. We need the program error output.

I don't know which Desktop Environment you're using. It needs to support XEmbed. There's also support for SNI, but in that case you'd need to have statusnotifier available as described in the readme.

**Comment by raven2cz** [comment]
In addition, do you manually copy data/apps.volctl.gschema.xml to /usr/share/glib-2.0/schemas/ first?

**Comment by KiritoStorm** [comment]
I'm using Gnome as desktop enviroment and I have copied that manually yes.
Is there a way how I can see the programm error output easily? Or should a try a other terminal to see the output?

Anyways thank you for trying to help :heart:

**Comment by raven2cz** [comment]
Just start program from terminal, type command `volctl` to console and copy the output from it.

**Comment by buzz** [comment]
> I'm using Gnome as desktop enviroment and I have copied that manually yes.

I think Gnome dropped support for status icons some time ago. Did you try something like this? https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by KiritoStorm** [comment]
I'm using the Gnome enviroment and yes I copied this.
Where can I get the programm output? Or should I try a other terminal to see an output?

Anyways thank you for trying to help me. :heart:

**Comment by buzz** [comment]
Closed for inactivity.
