### ISSUE TITLE
Remove pulseaudio as a dependency in AUR package

### ISSUE THREAD

**Issue by snprajwal** [buzz/volctl#63]
I am currently using volctl with pipewire and it works fine. We should remove pulse as a dependency and leave it to the user to decide what sound server they utilise volctl with.

**Comment by RiedleroD** [comment]
in the arch repos, pipewire-pulse provides pulseaudio (as in: satisfies the dependency), so there's no action needed there.

**Comment by buzz** [comment]
what @RiedleroD said...

**Comment by RiedleroD** [comment]
also, as a final note: the developers are rarely the same people that package their software, so if there's any problem with a package, email the packager instead. Depending on the package manager you're using, there may be a way to see the email address of the packager. On arch Linux it's `pacman -Si <packagename>`
