### ISSUE TITLE
Launch option for detached/oneshot usages.

### ISSUE THREAD

**Issue by tkapias** [buzz/volctl#64]
Thanks for this application.

**Is it possible to add an option to volctl to launch it as a detached & temporary instance without tray icon?**

I'm using [Polybar](https://github.com/polybar/polybar) with the ["Pulseaudio"](https://github.com/polybar/polybar/wiki/Module:-pulseaudio) module. There is a tray area, but I would like to have as few icons as possible there.

I would like volctl to run from the command line at the cursor position and close when clicked outside. For example, with an option --oneshot or --detached.

Then we could incorporate it in Polybar as a module or as an action of the Pulseaudio module.

*For reference, that is how I use [Gsimplecal](https://github.com/dmedvinsky/gsimplecal) with the Polybar ["Date"](https://github.com/polybar/polybar/wiki/Module:-date) module as an [action](https://github.com/polybar/polybar/wiki/Formatting#action-a).*

**Comment by buzz** [comment]
volctl main and sole purpose is being a tray icon. I think you have a very special use case and it might be worth creating a separate project. I won't have the time to support such behavior, I'm afraid.
