### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by DafelixCly** [buzz/volctl#68]
I just want to change the icon and the colors, but I can´t find any config file or command to do that.

**Comment by buzz** [comment]
What do you exactly mean by *the icon and the colors*?

**Comment by DafelixCly** [comment]
When I start Volctl it creates an applet (as peaker icon), and when I press it it opens a little white window with volume sliders and icons for each one. I want to change the applet icon and make the mixer window dark. Is there a config file? Where does volctl get the icons and color schemes?

**Comment by buzz** [comment]
The application uses plain icon names: `audio-volume-low`, `audio-volume-medium`, `audio-volume-high` or `audio-volume-muted` as specified by the [Icon Naming Specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html).

This means the actual icons that you see on your screen are not chosen by volctl. *Changing* those icons involves installing and enabling a different icon theme. The same is true for *colors*. How windows are drawn depends on your GTK3 theme setting.

This is the file: `.config/gtk-3.0/settings.ini`. The settings keys are `gtk-icon-theme-name` and `gtk-theme-name`. Refer to the [Arch wiki](https://wiki.archlinux.org/title/GTK) for more detail on the topic.

**Comment by gitaarik** [comment]
Hey, I'm also trying to make this work. I am switching between dark/light theme with the `.config/gtk-3.0/settings.ini` and `.config/gtk-4.0/settings.ini` files. I tried them both with these configs:

#### Dark  theme:
```
gtk-theme-name=Adwaita-dark
gtk-icon-theme-name=Adwaita
gtk-cursor-theme-name=Adwaita
gtk-application-prefer-dark-theme=1
```

#### Light theme:
```
gtk-theme-name=Adwaita-light
gtk-icon-theme-name=Adwaita
gtk-cursor-theme-name=Adwaita
gtk-application-prefer-dark-theme=0
```

But for both configs, for both gtk-3.0 and gtk-4.0, it seems to have no effect on the icons of volctl. Also putting the `-dark` or `-light` prefix behind the `gtk-icon-theme-name` or `gtk-cursor-theme-name` doesn't make a difference.

### Screenshots:

### Dark  theme
![image](https://user-images.githubusercontent.com/2470302/210883061-4b9995a5-b914-4711-9f07-8c1fafdb38a6.png)

### Light theme:
![image](https://user-images.githubusercontent.com/2470302/210882973-9e4f5542-8b6f-49f3-aec0-d2e4bf2aa57d.png)
