### ISSUE TITLE
Mouse wheel step resets itself

### ISSUE THREAD

**Issue by onli** [buzz/volctl#73]
Steps to reproduce: Open the preferences. "Mouse wheel step" is at 15%. Slide it down to 3%. Close the preferences. Open the preferences.

Expected result: Mouse wheel step is at 3%.

Actual result: Mouse wheel step is at 15%.

Until the program is restarted the actual step size stays at 3%, but a restart resets it to 15% also in the functionality, not only in the UI.

Environment:  v0.9.2 (from the void repository), custom icewm desktop.

**Comment by buzz** [comment]
I'm unable to repro.

volctl uses `Gio.Settings` to store/retrieve configuration. Maybe there's something wrong with it on your box?

**Comment by onli** [comment]
It is likely that the fault is in the settings layer. I'm not using gnome.

I'm also not able to reproduce it right now. It was broken so long that I had switched to a different tray control program, now it seems to work - possible that a system upgrade helped?

I will re-open if the error occurs again, maybe we can find a way to pinpoint it then. But let's assume it's fixed for now.
