### ISSUE TITLE
Fails with `module 'pulsectl._pulsectl' has no attribute 'PA_SAMPLE_FLOAT32B`

### ISSUE THREAD

**Issue by stratosgear** [buzz/volctl#76]
I am on latest arch and I  used to have volctl install on a previous system but on my new one it fails with:

```
[stratos@iocaine bin]$ volctl
Traceback (most recent call last):
  File "/usr/bin/volctl", line 33, in <module>
    sys.exit(load_entry_point('volctl==0.9.3', 'gui_scripts', 'volctl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/volctl/__main__.py", line 20, in main
    app = VolctlApp()
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/volctl/app.py", line 53, in __init__
    self.pulsemgr = PulseManager(self)
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/volctl/pulsemgr.py", line 83, in __init__
    format=c.PA_SAMPLE_FLOAT32BE, rate=25, channels=1
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pulsectl._pulsectl' has no attribute 'PA_SAMPLE_FLOAT32BE'. Did you mean: 'PA_SAMPLE_FLOAT32NE'?
```

Am I missing any packages...? The error message looks like a compilation error, and I am not sure...

Thanks

**Comment by raven2cz** [comment]
Arch had upgrade from 3.10 to 3.11. Did you really compile all deps, or just volctl?

You have to compile it with

You have to just rebuild Python aur packages with Python 3.11. No all can be signed for rebuild in deps. 
```
    paru -S --rebuild --noconfirm $(paru -Qqo /usr/lib/python3.10/)
    yay -S --rebuild --noconfirm $(yay -Qqo /usr/lib/python3.10/)
```

**Comment by raven2cz** [comment]
Sorry, it seems that it really broken and it has to be migrated to 3.11. It was possible to compile yesterday in several stations. But it is not possible to compile in one station today. Same problem:

AttributeError: module 'pulsectl._pulsectl' has no attribute 'PA_SAMPLE_FLOAT32BE'. Did you mean: 'PA_SAMPLE_FLOAT32NE'?

**Comment by raven2cz** [comment]
https://github.com/mk-fg/python-pulse-control/issues/78

hmmmm, @buzz we have to modify it. It is in-compatible now.

**Comment by mk-fg** [comment]
I've restored these constants in 23.5.1, but note that it won't fix the issue!
That constant was set to a wrong value in the first-place, and two mistakes in both its name and value kinda cancelled each other out - see https://github.com/mk-fg/python-pulse-control/issues/76 for details.

It's obviously a bad idea to depend on internal underscored-anything, especially a module like that, but if there's no better way around it, at least changing constant to PA_SAMPLE_FLOAT32LE might be necessary (which is =5, same as BE was incorrectly set to there), though maybe a better idea would be to use NE value, if native-endiannes float ctype is used here as well.

A better fix might be to move some needed stuff out from there into either volctl or pulsectl.

**Comment by raven2cz** [comment]
Thanks, I try to inform buzz from volctl. I hope that he has time to fix it. I create MR for faster understanding the problem.

**Comment by t3pfaffe** [comment]
Simply changing the code in volctl/pulsemgr.py from
https://github.com/buzz/volctl/blob/2d173bcb8e139846eccd23b8af22b2e836e4f877/volctl/pulsemgr.py#L83

to 
`format=c.PA_SAMPLE_FLOAT32NE, rate=25, channels=1`

fixes the issue.

**Comment by stratosgear** [comment]
I confirm that version [v0.9.4] is now installable!  

Thanks!
