### ISSUE TITLE
Wait for tray 

### ISSUE THREAD

**Issue by musjj** [buzz/volctl#81]
Is there a way to wait for the tray before erroring out? I have a service like this:

```service
[Install]
WantedBy=tray.target

[Service]
ExecStart=/usr/bin/volctl

[Unit]
Description=Per-application volume control and OSD for Linux desktops
PartOf=tray.target
```

But it errors on startup because the tray is not ready yet:

```bash
Aug 28 08:36:28 $HOST volctl[1362]: PulseAudio connected
Aug 28 08:36:28 $HOST volctl[1362]: Warning: Could not embed Gtk.StatusIcon.
Aug 28 08:36:28 $HOST volctl[1362]: Fatal error: Could not create a status icon. Are you sure you have a working notification area?
Aug 28 08:36:28 $HOST volctl[1362]: pulseaudio disconnected
Aug 28 08:36:28 $HOST systemd[1324]: volctl.service: Main process exited, code=killed, status=14/ALRM
Aug 28 08:36:28 $HOST systemd[1324]: volctl.service: Failed with result 'signal'.
```

Other tray services does not seem to have this problem. Is there a way to handle this problem?

**Comment by raven2cz** [comment]
This issue has surfaced approximately four weeks ago. It seems likely that the root cause may be a modification in PulseAudio, its API, or some other related library. This is noteworthy because Volctl, which has been stable for several years, hasn't undergone any changes that could explain this new problem. Unfortunately, due to time constraints, I haven't been able to investigate the cause of this unexpected behavior.

**Comment by musjj** [comment]
It looks like the problem is not with pulseaudio but with it failing to create a status icon. Can you clarify?

**Comment by raven2cz** [comment]
A few weeks ago, something changed that affected the functionality, but not within Volctl itself. The link you provided is relevant; I'm experiencing the same issue now. As a temporary solution, I've had to adjust the initialization settings of Volctl and set a waiting time. However, this is merely a workaround and not a proper solution to the problem.

**Comment by musjj** [comment]
Looks like the fix is pretty simple. The culprit is this line:

https://github.com/buzz/volctl/blob/cf0f7edc9da2735d2e1565cb5d2a43d92d917412/volctl/status_icon.py#L119

Removing it fixes the problem.

It tries to check if icon is embedded or not, but I'm not really sure if it's necessary. It'll automatically embed itself when the tray is ready.

I'm guessing that it's intended to check if there's a problem, but isn't there a better way? I'd assume that as long as `Gtk.StatusIcon()` isn't throwing any exceptions, things should work just fine.

**Comment by raven2cz** [comment]
Nice! Try to create PR and @buzz look on it, thx!

**Comment by musjj** [comment]
I'm not really sure how well it works with Wayland though. What happens when `statusnotifier` isn't installed when `volctl` is launched? Will `Gtk.StatusIcon` fail silently or does it correctly throw an error?

**Comment by buzz** [comment]
> I'm not really sure how well it works with Wayland though. What happens when `statusnotifier` isn't installed when `volctl` is launched? Will `Gtk.StatusIcon` fail silently or does it correctly throw an error?

This issue is not related to Wayland. Check #39 instead.

**Comment by musjj** [comment]
I think you misunderstood my comment. What I am asking is the impact of the change I proposed above on Wayland systems. The solution above works perfectly on X for me, but since I don't use Wayland, I can't predict what kind of impact it would have.

But it seems that `volctl` isn't actually supported on Wayland at all, so I guess it doesn't really matter.
