### ISSUE TITLE
changing osd icon on the screen. adding missing documentation.

### ISSUE THREAD

**Issue by beastr45** [buzz/volctl#82]
would like to know if volctl has a configuration file in order to change the position or style of the osd display. It would also be cool to disable the osd if you want only the systray app.  It would be awesome to add that documentation to the readme or elsewhere.

**Comment by buzz** [comment]
> would like to know if volctl has a configuration file 

volctl uses GSettings for storing configuration. So, no, there's no configuration file.

> change the position or style of the osd display. It would also be cool to disable the osd

It can already be done. Find the section "On-screen display" under "Preferences".

> It would be awesome to add that documentation to the readme or elsewhere.

Add what exactly to the documentation?

All settings are documented inside the software. Just hover over the individual fields and there should be a tooltip. If you prefer non-GUI workflow, you can always read the GSettings schema.

Apart from that, feel free to improve on documentation. Contributions are always welcome.

**Comment by beastr45** [comment]
> > would like to know if volctl has a configuration file
> 
> volctl uses GSettings for storing configuration. So, no, there's no configuration file.
> 
> > change the position or style of the osd display. It would also be cool to disable the osd
> 
> It can already be done. Find the section "On-screen display" under "Preferences".
> 
> > It would be awesome to add that documentation to the readme or elsewhere.
> 
> Add what exactly to the documentation?
> 
> All settings are documented inside the software. Just hover over the individual fields and there should be a tooltip. If you prefer non-GUI workflow, you can always read the GSettings schema.
> 
> Apart from that, feel free to improve on documentation. Contributions are always welcome.

shure i didnt find the settings menu

**Comment by beastr45** [comment]
closed
